$ErrorActionPreference="Stop"
Set-StrictMode -Version Latest
function Die([string]$m){ throw $m }

function Write-Utf8NoBomLf([string]$Path,[string]$Text){
  $dir = Split-Path -Parent $Path
  if($dir -and -not (Test-Path -LiteralPath $dir -PathType Container)){
    New-Item -ItemType Directory -Force -Path $dir | Out-Null
  }
  $t = $Text -replace "`r`n","`n"
  $t = $t -replace "`r","`n"
  if(-not $t.EndsWith("`n")){ $t += "`n" }
  $enc = New-Object System.Text.UTF8Encoding($false)
  [System.IO.File]::WriteAllText($Path,$t,$enc)
}

function Parse-GatePs1([string]$Path){
  if(-not (Test-Path -LiteralPath $Path -PathType Leaf)){ Die ("MISSING_FILE: " + $Path) }
  $tokens = $null
  $errors = $null
  [void][System.Management.Automation.Language.Parser]::ParseFile($Path,[ref]$tokens,[ref]$errors)
  if($errors -and $errors.Count -gt 0){
    $e = $errors[0]
    Die ("PARSE_GATE_FAIL: " + $Path + " @ " + $e.Extent.StartLineNumber + ":" + $e.Extent.StartColumnNumber + " " + $e.Message)
  }
}

function Assert-Utf8NoBomLfFile([string]$Path){
  if(-not (Test-Path -LiteralPath $Path -PathType Leaf)){ Die ("MISSING_FILE: " + $Path) }
  $b = [System.IO.File]::ReadAllBytes($Path)

  # UTF-8 BOM check (EF BB BF)
  if($b.Length -ge 3 -and $b[0] -eq 0xEF -and $b[1] -eq 0xBB -and $b[2] -eq 0xBF){
    Die ("BOM_PRESENT_NOT_ALLOWED: " + $Path)
  }

  # CR byte check (0x0D) — must be LF-only
  for($i=0; $i -lt $b.Length; $i++){
    if($b[$i] -eq 13){
      Die ("CR_BYTE_NOT_ALLOWED: " + $Path + " @index=" + $i)
    }
  }
}

$RepoRoot = (Resolve-Path -LiteralPath ".").Path

$DocPath  = Join-Path $RepoRoot "docs\SELFTEST_ProteusOps_v0_1.md"
$RunPath  = Join-Path $RepoRoot "scripts\selftest_all.ps1"
$JsBooking = Join-Path $RepoRoot "selftest_booking.js"
$JsDisabled = Join-Path $RepoRoot "selftest_booking_disabled.js"

# =========================================================
# 1) docs/SELFTEST_ProteusOps_v0_1.md (FULL REWRITE)
# =========================================================
$doc = New-Object System.Collections.Generic.List[string]
[void]$doc.Add('# SELFTEST — ProteusOps v0.1 (Storefront + Booking)')
[void]$doc.Add('')
[void]$doc.Add('## Purpose (Tier-0 proof)')
[void]$doc.Add('')
[void]$doc.Add('Prove (deterministically) that ProteusOps enforces:')
[void]$doc.Add('')
[void]$doc.Add('- Billing entitlements in the database (no UI tricks)')
[void]$doc.Add('- Feature gating in the database (booking_enabled + paid_active)')
[void]$doc.Add('- Booking integrity in the database (availability / overlap / time-off with stable failure tokens)')
[void]$doc.Add('- “No direct writes” posture for booking tables (RPC-only surfaces)')
[void]$doc.Add('')
[void]$doc.Add('This selftest is a proof-run, not a product UX.')
[void]$doc.Add('')
[void]$doc.Add('---')
[void]$doc.Add('')
[void]$doc.Add('## Important Note (Supabase SQL Editor)')
[void]$doc.Add('')
[void]$doc.Add('Supabase SQL Editor runs without an authenticated user context:')
[void]$doc.Add('')
[void]$doc.Add('- auth.uid() is null')
[void]$doc.Add('- auth.role() is typically not authenticated')
[void]$doc.Add('- Any RPC that requires auth.uid() will raise AUTH_REQUIRED')
[void]$doc.Add('')
[void]$doc.Add('Therefore the official Tier-0 selftest path for authenticated behavior is Node scripts, not SQL Editor.')
[void]$doc.Add('')
[void]$doc.Add('---')
[void]$doc.Add('')
[void]$doc.Add('## Canonical selftest entry points')
[void]$doc.Add('')
[void]$doc.Add('A) Authenticated selftest (positive booking gates)')
[void]$doc.Add('- node selftest_booking.js')
[void]$doc.Add('')
[void]$doc.Add('B) Service-role selftest (plan flip → BOOKING_DISABLED → restore)')
[void]$doc.Add('- node selftest_booking_disabled.js')
[void]$doc.Add('')
[void]$doc.Add('C) One-command FULL_GREEN runner')
[void]$doc.Add('- powershell.exe -NoProfile -NonInteractive -ExecutionPolicy Bypass -File scripts\selftest_all.ps1')
[void]$doc.Add('')
[void]$doc.Add('---')
[void]$doc.Add('')
[void]$doc.Add('## Preconditions')
[void]$doc.Add('')
[void]$doc.Add('### Required environment variables (Process env)')
[void]$doc.Add('')
[void]$doc.Add('- SUPABASE_URL')
[void]$doc.Add('- SUPABASE_ANON_KEY')
[void]$doc.Add('- TEST_EMAIL')
[void]$doc.Add('- TEST_PASSWORD')
[void]$doc.Add('- ORG_ID')
[void]$doc.Add('- SUPABASE_SERVICE_ROLE_KEY (required only for selftest_booking_disabled.js / selftest_all.ps1)')
[void]$doc.Add('')
[void]$doc.Add('### Required database surfaces')
[void]$doc.Add('')
[void]$doc.Add('Public (PostgREST exposed) wrappers must exist:')
[void]$doc.Add('- public.rpc_selftest_reset_booking_v1(uuid, uuid)')
[void]$doc.Add('- public.rpc_upsert_availability_rule_v1(...)')
[void]$doc.Add('- public.rpc_create_appointment_v1(...)')
[void]$doc.Add('- public.rpc_add_time_off_block_v1(...)')
[void]$doc.Add('- public.rpc_recompute_entitlements(uuid)')
[void]$doc.Add('- public.rpc_selftest_set_subscription_plan_v1(uuid, text, text)  (service-role only)')
[void]$doc.Add('')
[void]$doc.Add('Plans/capabilities must exist and recompute must materialize them into pods.org_entitlements.')
[void]$doc.Add('')
[void]$doc.Add('---')
[void]$doc.Add('')
[void]$doc.Add('## Expected tokens')
[void]$doc.Add('')
[void]$doc.Add('selftest_booking.js (positive path):')
[void]$doc.Add('- SELFTEST_RESET_OK')
[void]$doc.Add('- AVAILABILITY_OK')
[void]$doc.Add('- APPOINTMENT_CREATE_OK')
[void]$doc.Add('- OVERLAP_TEST_EXPECTED_FAIL token=APPOINTMENT_OVERLAP')
[void]$doc.Add('- TIMEOFF_OK')
[void]$doc.Add('- TIMEOFF_TEST_EXPECTED_FAIL token=STAFF_TIME_OFF_BLOCK')
[void]$doc.Add('- SELFTEST_DONE')
[void]$doc.Add('')
[void]$doc.Add('selftest_booking_disabled.js (negative plan flip):')
[void]$doc.Add('- PLAN_FLIP_OK plan_id=proteusops_s_v1 recompute=ok')
[void]$doc.Add('- BOOKING_DISABLED_TEST_EXPECTED_FAIL token=BOOKING_DISABLED')
[void]$doc.Add('- PLAN_RESTORE_OK plan_id=proteusops_sb_v1 recompute=ok')
[void]$doc.Add('- SELFTEST_DONE')
[void]$doc.Add('')
[void]$doc.Add('---')
[void]$doc.Add('')
[void]$doc.Add('## Notes')
[void]$doc.Add('')
[void]$doc.Add('- These tests intentionally prove DB enforcement (RLS + RPC gates + entitlement recompute).')
[void]$doc.Add('- SQL Editor is not used for authenticated paths because auth.uid() is null there.')

Write-Utf8NoBomLf $DocPath ((@($doc.ToArray()) -join "`n") + "`n")
Assert-Utf8NoBomLfFile $DocPath
Write-Host ("WROTE+DOC_UTF8_LF_OK: " + $DocPath) -ForegroundColor Green

# =========================================================
# 2) selftest_booking.js (FULL REWRITE, ESM)
# =========================================================
$js1 = New-Object System.Collections.Generic.List[string]
[void]$js1.Add('import { createClient } from "@supabase/supabase-js";')
[void]$js1.Add('')
[void]$js1.Add('const url = process.env.SUPABASE_URL;')
[void]$js1.Add('const anon = process.env.SUPABASE_ANON_KEY;')
[void]$js1.Add('const email = process.env.TEST_EMAIL;')
[void]$js1.Add('const password = process.env.TEST_PASSWORD;')
[void]$js1.Add('const ORG_ID = process.env.ORG_ID;')
[void]$js1.Add('')
[void]$js1.Add('function req(name, v) {')
[void]$js1.Add('  if (!v || !String(v).trim()) throw new Error(`MISSING_ENV_${name}`);')
[void]$js1.Add('  return v;')
[void]$js1.Add('}')
[void]$js1.Add('')
[void]$js1.Add('async function rpc(supabase, fn, args) {')
[void]$js1.Add('  const { data, error } = await supabase.rpc(fn, args);')
[void]$js1.Add('  if (error) throw error;')
[void]$js1.Add('  return data;')
[void]$js1.Add('}')
[void]$js1.Add('')
[void]$js1.Add('function pickSlotLocal() {')
[void]$js1.Add('  // Deterministic: choose local 10:00–11:00 tomorrow if now already past 10:00, else today.')
[void]$js1.Add('  const now = new Date();')
[void]$js1.Add('  let start = new Date(now.getFullYear(), now.getMonth(), now.getDate(), 10, 0, 0, 0);')
[void]$js1.Add('  if (start.getTime() <= now.getTime()) {')
[void]$js1.Add('    start = new Date(now.getFullYear(), now.getMonth(), now.getDate() + 1, 10, 0, 0, 0);')
[void]$js1.Add('  }')
[void]$js1.Add('  const end = new Date(start.getTime() + 60 * 60 * 1000);')
[void]$js1.Add('  return { start, end, dow: start.getDay() };')
[void]$js1.Add('}')
[void]$js1.Add('')
[void]$js1.Add('async function main() {')
[void]$js1.Add('  req("SUPABASE_URL", url);')
[void]$js1.Add('  req("SUPABASE_ANON_KEY", anon);')
[void]$js1.Add('  req("TEST_EMAIL", email);')
[void]$js1.Add('  req("TEST_PASSWORD", password);')
[void]$js1.Add('  req("ORG_ID", ORG_ID);')
[void]$js1.Add('')
[void]$js1.Add('  const supabase = createClient(url, anon);')
[void]$js1.Add('')
[void]$js1.Add('  const { data: authData, error: authErr } = await supabase.auth.signInWithPassword({ email, password });')
[void]$js1.Add('  if (authErr) throw authErr;')
[void]$js1.Add('  const userId = authData.user.id;')
[void]$js1.Add('  console.log("AUTH_OK user_id=", userId);')
[void]$js1.Add('  console.log("ORG_ID=", ORG_ID);')
[void]$js1.Add('')
[void]$js1.Add('  // 0) reset booking rows for this org+staff via authenticated wrapper')
[void]$js1.Add('  await rpc(supabase, "rpc_selftest_reset_booking_v1", { p_org_id: ORG_ID, p_staff_user_id: userId });')
[void]$js1.Add('  console.log("SELFTEST_RESET_OK");')
[void]$js1.Add('')
[void]$js1.Add('  const { start, end, dow } = pickSlotLocal();')
[void]$js1.Add('')
[void]$js1.Add('  // 1) availability for that dow')
[void]$js1.Add('  const ruleId = await rpc(supabase, "rpc_upsert_availability_rule_v1", {')
[void]$js1.Add('    p_org_id: ORG_ID,')
[void]$js1.Add('    p_rule_id: null,')
[void]$js1.Add('    p_staff_user_id: userId,')
[void]$js1.Add('    p_location_id: null,')
[void]$js1.Add('    p_day_of_week: dow,')
[void]$js1.Add('    p_start_time: "09:00:00",')
[void]$js1.Add('    p_end_time: "17:00:00",')
[void]$js1.Add('    p_is_active: true,')
[void]$js1.Add('  });')
[void]$js1.Add('  console.log("AVAILABILITY_OK rule_id=", ruleId, "dow=", dow);')
[void]$js1.Add('')
[void]$js1.Add('  // 2) create appointment inside availability')
[void]$js1.Add('  const apptId1 = await rpc(supabase, "rpc_create_appointment_v1", {')
[void]$js1.Add('    p_org_id: ORG_ID,')
[void]$js1.Add('    p_staff_user_id: userId,')
[void]$js1.Add('    p_start_time: start.toISOString(),')
[void]$js1.Add('    p_end_time: end.toISOString(),')
[void]$js1.Add('    p_service_id: null,')
[void]$js1.Add('    p_location_id: null,')
[void]$js1.Add('    p_guest_name: "Guest One",')
[void]$js1.Add('    p_guest_email: "guest@example.com",')
[void]$js1.Add('    p_guest_phone: "555-0100",')
[void]$js1.Add('    p_notes: "selftest:appt1",')
[void]$js1.Add('  });')
[void]$js1.Add('  console.log("APPOINTMENT_CREATE_OK appointment_id=", apptId1);')
[void]$js1.Add('')
[void]$js1.Add('  // 3) overlap test (expected APPOINTMENT_OVERLAP)')
[void]$js1.Add('  try {')
[void]$js1.Add('    await rpc(supabase, "rpc_create_appointment_v1", {')
[void]$js1.Add('      p_org_id: ORG_ID,')
[void]$js1.Add('      p_staff_user_id: userId,')
[void]$js1.Add('      p_start_time: start.toISOString(),')
[void]$js1.Add('      p_end_time: end.toISOString(),')
[void]$js1.Add('      p_service_id: null,')
[void]$js1.Add('      p_location_id: null,')
[void]$js1.Add('      p_guest_name: "Guest Two",')
[void]$js1.Add('      p_guest_email: "guest2@example.com",')
[void]$js1.Add('      p_guest_phone: "555-0101",')
[void]$js1.Add('      p_notes: "selftest:overlap",')
[void]$js1.Add('    });')
[void]$js1.Add('    console.log("OVERLAP_TEST_UNEXPECTED_OK");')
[void]$js1.Add('    process.exit(2);')
[void]$js1.Add('  } catch (e) {')
[void]$js1.Add('    console.log("OVERLAP_TEST_EXPECTED_FAIL token=", e?.message || String(e));')
[void]$js1.Add('  }')
[void]$js1.Add('')
[void]$js1.Add('  // 4) timeoff block test (expected STAFF_TIME_OFF_BLOCK)')
[void]$js1.Add('  const startTO = new Date(end.getTime() + 30 * 60 * 1000);')
[void]$js1.Add('  const endTO = new Date(startTO.getTime() + 60 * 60 * 1000);')
[void]$js1.Add('  const blockId = await rpc(supabase, "rpc_add_time_off_block_v1", {')
[void]$js1.Add('    p_org_id: ORG_ID,')
[void]$js1.Add('    p_staff_user_id: userId,')
[void]$js1.Add('    p_start_time: startTO.toISOString(),')
[void]$js1.Add('    p_end_time: endTO.toISOString(),')
[void]$js1.Add('    p_reason: "selftest:timeoff",')
[void]$js1.Add('  });')
[void]$js1.Add('  console.log("TIMEOFF_OK block_id=", blockId);')
[void]$js1.Add('')
[void]$js1.Add('  try {')
[void]$js1.Add('    await rpc(supabase, "rpc_create_appointment_v1", {')
[void]$js1.Add('      p_org_id: ORG_ID,')
[void]$js1.Add('      p_staff_user_id: userId,')
[void]$js1.Add('      p_start_time: startTO.toISOString(),')
[void]$js1.Add('      p_end_time: endTO.toISOString(),')
[void]$js1.Add('      p_service_id: null,')
[void]$js1.Add('      p_location_id: null,')
[void]$js1.Add('      p_guest_name: "Guest Three",')
[void]$js1.Add('      p_guest_email: "guest3@example.com",')
[void]$js1.Add('      p_guest_phone: "555-0102",')
[void]$js1.Add('      p_notes: "selftest:timeoff-appt",')
[void]$js1.Add('    });')
[void]$js1.Add('    console.log("TIMEOFF_TEST_UNEXPECTED_OK");')
[void]$js1.Add('    process.exit(3);')
[void]$js1.Add('  } catch (e) {')
[void]$js1.Add('    console.log("TIMEOFF_TEST_EXPECTED_FAIL token=", e?.message || String(e));')
[void]$js1.Add('  }')
[void]$js1.Add('')
[void]$js1.Add('  console.log("SELFTEST_DONE");')
[void]$js1.Add('}')
[void]$js1.Add('')
[void]$js1.Add('main().catch((e) => {')
[void]$js1.Add('  console.error("SELFTEST_FATAL:", e);')
[void]$js1.Add('  process.exit(1);')
[void]$js1.Add('});')

Write-Utf8NoBomLf $JsBooking ((@($js1.ToArray()) -join "`n") + "`n")
Assert-Utf8NoBomLfFile $JsBooking
Write-Host ("WROTE+JS_UTF8_LF_OK: " + $JsBooking) -ForegroundColor Green

# =========================================================
# 3) selftest_booking_disabled.js (FULL REWRITE, ESM)
# =========================================================
$js2 = New-Object System.Collections.Generic.List[string]
[void]$js2.Add('import { createClient } from "@supabase/supabase-js";')
[void]$js2.Add('')
[void]$js2.Add('const url = process.env.SUPABASE_URL;')
[void]$js2.Add('const anon = process.env.SUPABASE_ANON_KEY;')
[void]$js2.Add('const service = process.env.SUPABASE_SERVICE_ROLE_KEY;')
[void]$js2.Add('const email = process.env.TEST_EMAIL;')
[void]$js2.Add('const password = process.env.TEST_PASSWORD;')
[void]$js2.Add('const ORG_ID = process.env.ORG_ID;')
[void]$js2.Add('')
[void]$js2.Add('function req(name, v) {')
[void]$js2.Add('  if (!v || !String(v).trim()) throw new Error(`MISSING_ENV_${name}`);')
[void]$js2.Add('  return v;')
[void]$js2.Add('}')
[void]$js2.Add('')
[void]$js2.Add('async function rpc(supabase, fn, args) {')
[void]$js2.Add('  const { data, error } = await supabase.rpc(fn, args);')
[void]$js2.Add('  if (error) throw error;')
[void]$js2.Add('  return data;')
[void]$js2.Add('}')
[void]$js2.Add('')
[void]$js2.Add('async function main() {')
[void]$js2.Add('  req("SUPABASE_URL", url);')
[void]$js2.Add('  req("SUPABASE_ANON_KEY", anon);')
[void]$js2.Add('  req("SUPABASE_SERVICE_ROLE_KEY", service);')
[void]$js2.Add('  req("TEST_EMAIL", email);')
[void]$js2.Add('  req("TEST_PASSWORD", password);')
[void]$js2.Add('  req("ORG_ID", ORG_ID);')
[void]$js2.Add('')
[void]$js2.Add('  const svc = createClient(url, service); // service-role context (RPC-only)')
[void]$js2.Add('  const user = createClient(url, anon);   // user context (auth + booking RPC)')
[void]$js2.Add('')
[void]$js2.Add('  const { data: authData, error: authErr } = await user.auth.signInWithPassword({ email, password });')
[void]$js2.Add('  if (authErr) throw authErr;')
[void]$js2.Add('  const userId = authData.user.id;')
[void]$js2.Add('  console.log("AUTH_OK user_id=", userId);')
[void]$js2.Add('  console.log("ORG_ID=", ORG_ID);')
[void]$js2.Add('')
[void]$js2.Add('  // 1) Flip plan to S (booking disabled) via service-role RPC and recompute')
[void]$js2.Add('  await rpc(svc, "rpc_selftest_set_subscription_plan_v1", {')
[void]$js2.Add('    p_org_id: ORG_ID,')
[void]$js2.Add('    p_plan_id: "proteusops_s_v1",')
[void]$js2.Add('    p_status: "trialing",')
[void]$js2.Add('  });')
[void]$js2.Add('  await rpc(svc, "rpc_recompute_entitlements", { p_org_id: ORG_ID });')
[void]$js2.Add('  console.log("PLAN_FLIP_OK plan_id=proteusops_s_v1 recompute=ok");')
[void]$js2.Add('')
[void]$js2.Add('  // 2) Attempt booking and assert BOOKING_DISABLED')
[void]$js2.Add('  try {')
[void]$js2.Add('    await rpc(user, "rpc_create_appointment_v1", {')
[void]$js2.Add('      p_org_id: ORG_ID,')
[void]$js2.Add('      p_staff_user_id: userId,')
[void]$js2.Add('      p_start_time: new Date(Date.now() + 24 * 60 * 60 * 1000).toISOString(),')
[void]$js2.Add('      p_end_time: new Date(Date.now() + 25 * 60 * 60 * 1000).toISOString(),')
[void]$js2.Add('      p_service_id: null,')
[void]$js2.Add('      p_location_id: null,')
[void]$js2.Add('      p_guest_name: "Guest Disabled",')
[void]$js2.Add('      p_guest_email: "disabled@example.com",')
[void]$js2.Add('      p_guest_phone: "555-0999",')
[void]$js2.Add('      p_notes: "selftest:disabled",')
[void]$js2.Add('    });')
[void]$js2.Add('    console.log("BOOKING_DISABLED_TEST_UNEXPECTED_OK");')
[void]$js2.Add('    process.exit(2);')
[void]$js2.Add('  } catch (e) {')
[void]$js2.Add('    const msg = e?.message || String(e);')
[void]$js2.Add('    if (msg !== "BOOKING_DISABLED") {')
[void]$js2.Add('      console.log("BOOKING_DISABLED_TEST_FAIL wrong_token=", msg);')
[void]$js2.Add('      process.exit(3);')
[void]$js2.Add('    }')
[void]$js2.Add('    console.log("BOOKING_DISABLED_TEST_EXPECTED_FAIL token=BOOKING_DISABLED");')
[void]$js2.Add('  }')
[void]$js2.Add('')
[void]$js2.Add('  // 3) Restore plan to SB and recompute')
[void]$js2.Add('  await rpc(svc, "rpc_selftest_set_subscription_plan_v1", {')
[void]$js2.Add('    p_org_id: ORG_ID,')
[void]$js2.Add('    p_plan_id: "proteusops_sb_v1",')
[void]$js2.Add('    p_status: "trialing",')
[void]$js2.Add('  });')
[void]$js2.Add('  await rpc(svc, "rpc_recompute_entitlements", { p_org_id: ORG_ID });')
[void]$js2.Add('  console.log("PLAN_RESTORE_OK plan_id=proteusops_sb_v1 recompute=ok");')
[void]$js2.Add('')
[void]$js2.Add('  console.log("SELFTEST_DONE");')
[void]$js2.Add('}')
[void]$js2.Add('')
[void]$js2.Add('main().catch((e) => {')
[void]$js2.Add('  console.error("SELFTEST_FATAL:", e);')
[void]$js2.Add('  process.exit(1);')
[void]$js2.Add('});')

Write-Utf8NoBomLf $JsDisabled ((@($js2.ToArray()) -join "`n") + "`n")
Assert-Utf8NoBomLfFile $JsDisabled
Write-Host ("WROTE+JS_UTF8_LF_OK: " + $JsDisabled) -ForegroundColor Green

# =========================================================
# 4) scripts/selftest_all.ps1 (runner)
# =========================================================
$run = New-Object System.Collections.Generic.List[string]
[void]$run.Add('$ErrorActionPreference="Stop"')
[void]$run.Add('Set-StrictMode -Version Latest')
[void]$run.Add('function Die([string]$m){ throw $m }')
[void]$run.Add('')
[void]$run.Add('$RepoRoot = (Resolve-Path -LiteralPath ".").Path')
[void]$run.Add('$node = (Get-Command node.exe -ErrorAction Stop).Source')
[void]$run.Add('')
[void]$run.Add('function NeedEnv([string]$k){')
[void]$run.Add('  $v = [Environment]::GetEnvironmentVariable($k,"Process")')
[void]$run.Add('  if([string]::IsNullOrWhiteSpace($v)){ Die ("MISSING_ENV_" + $k) }')
[void]$run.Add('  return $v')
[void]$run.Add('}')
[void]$run.Add('')
[void]$run.Add('# Required for both scripts')
[void]$run.Add('[void](NeedEnv "SUPABASE_URL")')
[void]$run.Add('[void](NeedEnv "SUPABASE_ANON_KEY")')
[void]$run.Add('[void](NeedEnv "TEST_EMAIL")')
[void]$run.Add('[void](NeedEnv "TEST_PASSWORD")')
[void]$run.Add('[void](NeedEnv "ORG_ID")')
[void]$run.Add('')
[void]$run.Add('# Required for disabled plan flip script')
[void]$run.Add('[void](NeedEnv "SUPABASE_SERVICE_ROLE_KEY")')
[void]$run.Add('')
[void]$run.Add('function RunNode([string]$rel){')
[void]$run.Add('  $p = Join-Path $RepoRoot $rel')
[void]$run.Add('  if(-not (Test-Path -LiteralPath $p -PathType Leaf)){ Die ("MISSING_FILE: " + $p) }')
[void]$run.Add('  Write-Host ("RUN: node " + $rel) -ForegroundColor Cyan')
[void]$run.Add('  & $node $p | Out-Host')
[void]$run.Add('  if($LASTEXITCODE -ne 0){ Die ("NODE_FAIL: " + $rel + " exit=" + $LASTEXITCODE) }')
[void]$run.Add('}')
[void]$run.Add('')
[void]$run.Add('RunNode "selftest_booking.js"')
[void]$run.Add('RunNode "selftest_booking_disabled.js"')
[void]$run.Add('')
[void]$run.Add('Write-Host "FULL_GREEN_SELFTEST_OK" -ForegroundColor Green')

Write-Utf8NoBomLf $RunPath ((@($run.ToArray()) -join "`n") + "`n")
Parse-GatePs1 $RunPath
Write-Host ("WROTE+RUNNER_PARSE_OK: " + $RunPath) -ForegroundColor Green

Write-Host "PATCH_V3_OK" -ForegroundColor Green
