$ErrorActionPreference="Stop"
Set-StrictMode -Version Latest
function Die([string]$m){ throw $m }

function Write-Utf8NoBomLf([string]$Path,[string]$Text){
  $dir = Split-Path -Parent $Path
  if($dir -and -not (Test-Path -LiteralPath $dir -PathType Container)){
    New-Item -ItemType Directory -Force -Path $dir | Out-Null
  }
  $t = $Text -replace "`r`n","`n"
  $t = $t -replace "`r","`n"
  if(-not $t.EndsWith("`n")){ $t += "`n" }
  $enc = New-Object System.Text.UTF8Encoding($false)
  [System.IO.File]::WriteAllText($Path,$t,$enc)
}

function Parse-GateFile([string]$Path){
  if(-not (Test-Path -LiteralPath $Path -PathType Leaf)){ Die ("MISSING_FILE: " + $Path) }
  $tokens = $null
  $errors = $null
  [void][System.Management.Automation.Language.Parser]::ParseFile($Path,[ref]$tokens,[ref]$errors)
  if($errors -and $errors.Count -gt 0){
    $e = $errors[0]
    Die ("PARSE_GATE_FAIL: " + $Path + " @ " + $e.Extent.StartLineNumber + ":" + $e.Extent.StartColumnNumber + " " + $e.Message)
  }
}

$RepoRoot = (Resolve-Path -LiteralPath ".").Path
$DocPath  = Join-Path $RepoRoot "docs\SELFTEST_ProteusOps_v0_1.md"
$RunPath  = Join-Path $RepoRoot "scripts\selftest_all.ps1"

# -------------------------
# docs/SELFTEST_ProteusOps_v0_1.md (FULL REWRITE)
# -------------------------
$docLines = New-Object System.Collections.Generic.List[string]

[void]$docLines.Add('# SELFTEST — ProteusOps v0.1 (Storefront + Booking)')
[void]$docLines.Add('')
[void]$docLines.Add('## Purpose (Tier-0 proof)')
[void]$docLines.Add('')
[void]$docLines.Add('Prove (deterministically) that ProteusOps enforces:')
[void]$docLines.Add('')
[void]$docLines.Add('- Billing entitlements in the database (no UI tricks)')
[void]$docLines.Add('- Feature gating in the database (booking_enabled + paid_active)')
[void]$docLines.Add('- Booking integrity in the database (availability / overlap / time-off with stable failure tokens)')
[void]$docLines.Add('- “No direct writes” posture for booking tables (RPC-only surfaces)')
[void]$docLines.Add('')
[void]$docLines.Add('This selftest is a proof-run, not a product UX.')
[void]$docLines.Add('')
[void]$docLines.Add('---')
[void]$docLines.Add('')
[void]$docLines.Add('## Important Note (Supabase SQL Editor)')
[void]$docLines.Add('')
[void]$docLines.Add('Supabase SQL Editor runs without an authenticated user context:')
[void]$docLines.Add('')
[void]$docLines.Add('- auth.uid() is null')
[void]$docLines.Add('- auth.role() is typically not authenticated')
[void]$docLines.Add('- Any RPC that requires auth.uid() will raise AUTH_REQUIRED')
[void]$docLines.Add('')
[void]$docLines.Add('Therefore the official Tier-0 selftest path for authenticated behavior is Node scripts, not SQL Editor.')
[void]$docLines.Add('')
[void]$docLines.Add('---')
[void]$docLines.Add('')
[void]$docLines.Add('## Canonical Selftest Entry Points')
[void]$docLines.Add('')
[void]$docLines.Add('A) Authenticated selftest (positive booking gates)')
[void]$docLines.Add('- node selftest_booking.js')
[void]$docLines.Add('')
[void]$docLines.Add('B) Service-role selftest (plan flip → BOOKING_DISABLED → restore)')
[void]$docLines.Add('- node selftest_booking_disabled.js')
[void]$docLines.Add('')
[void]$docLines.Add('C) One-command FULL_GREEN runner')
[void]$docLines.Add('- powershell.exe -NoProfile -NonInteractive -ExecutionPolicy Bypass -File scripts\selftest_all.ps1')
[void]$docLines.Add('')
[void]$docLines.Add('---')
[void]$docLines.Add('')
[void]$docLines.Add('## Preconditions')
[void]$docLines.Add('')
[void]$docLines.Add('### Environment variables (Process env)')
[void]$docLines.Add('')
[void]$docLines.Add('Required for Node tests:')
[void]$docLines.Add('')
[void]$docLines.Add('- SUPABASE_URL')
[void]$docLines.Add('- SUPABASE_ANON_KEY')
[void]$docLines.Add('- SUPABASE_SERVICE_ROLE_KEY (only needed for selftest_booking_disabled.js)')
[void]$docLines.Add('- TEST_EMAIL')
[void]$docLines.Add('- TEST_PASSWORD')
[void]$docLines.Add('')
[void]$docLines.Add('### Database state')
[void]$docLines.Add('')
[void]$docLines.Add('- Migrations applied through the public surfaces you are testing.')
[void]$docLines.Add('- Required plan rows exist in pods.plan_tiers:')
[void]$docLines.Add('  - proteusops_s_v1')
[void]$docLines.Add('  - proteusops_sb_v1')
[void]$docLines.Add('- Required plan capabilities exist in pods.plan_capabilities:')
[void]$docLines.Add('  - storefront_enabled=true for both plans')
[void]$docLines.Add('  - booking_enabled=false for S')
[void]$docLines.Add('  - booking_enabled=true for SB')
[void]$docLines.Add('- Org exists and has an active/trialing subscription row:')
[void]$docLines.Add('  - pods.subscriptions contains the org row')
[void]$docLines.Add('  - pods.org_entitlements recompute works and materializes the plan capabilities')
[void]$docLines.Add('')
[void]$docLines.Add('### Public RPC exposure (PostgREST)')
[void]$docLines.Add('')
[void]$docLines.Add('These wrappers must exist in public:')
[void]$docLines.Add('')
[void]$docLines.Add('Authenticated:')
[void]$docLines.Add('- public.rpc_selftest_reset_booking_v1(uuid, uuid)')
[void]$docLines.Add('- public.rpc_upsert_availability_rule_v1(...)')
[void]$docLines.Add('- public.rpc_create_appointment_v1(...)')
[void]$docLines.Add('- public.rpc_add_time_off_block_v1(...)')
[void]$docLines.Add('')
[void]$docLines.Add('Service-role-only:')
[void]$docLines.Add('- public.rpc_selftest_set_subscription_plan_v1(uuid, text, text)')
[void]$docLines.Add('- public.rpc_recompute_entitlements(uuid)')
[void]$docLines.Add('')
[void]$docLines.Add('---')
[void]$docLines.Add('')
[void]$docLines.Add('## Step 1 — Seed plan tiers + capabilities (SQL, run once)')
[void]$docLines.Add('')
[void]$docLines.Add('Run in SQL Editor:')
[void]$docLines.Add('')
[void]$docLines.Add('```sql')
[void]$docLines.Add('insert into pods.plan_tiers(plan_id, name, is_active)')
[void]$docLines.Add('values (''proteusops_s_v1'', ''Tier S (Storefront)'', true)')
[void]$docLines.Add('on conflict (plan_id) do nothing;')
[void]$docLines.Add('')
[void]$docLines.Add('insert into pods.plan_tiers(plan_id, name, is_active)')
[void]$docLines.Add('values (''proteusops_sb_v1'', ''Tier S+B (Storefront + Booking)'', true)')
[void]$docLines.Add('on conflict (plan_id) do nothing;')
[void]$docLines.Add('')
[void]$docLines.Add('-- Storefront enabled for both')
[void]$docLines.Add('insert into pods.plan_capabilities(plan_id, capability_key, value_type, value_bool)')
[void]$docLines.Add('values')
[void]$docLines.Add('  (''proteusops_s_v1'',  ''storefront_enabled'', ''bool'', true),')
[void]$docLines.Add('  (''proteusops_sb_v1'', ''storefront_enabled'', ''bool'', true)')
[void]$docLines.Add('on conflict (plan_id, capability_key) do update')
[void]$docLines.Add('set value_bool = excluded.value_bool,')
[void]$docLines.Add('    value_type = excluded.value_type;')
[void]$docLines.Add('')
[void]$docLines.Add('-- Booking only for SB plan')
[void]$docLines.Add('insert into pods.plan_capabilities(plan_id, capability_key, value_type, value_bool)')
[void]$docLines.Add('values')
[void]$docLines.Add('  (''proteusops_s_v1'',  ''booking_enabled'', ''bool'', false),')
[void]$docLines.Add('  (''proteusops_sb_v1'', ''booking_enabled'', ''bool'', true)')
[void]$docLines.Add('on conflict (plan_id, capability_key) do update')
[void]$docLines.Add('set value_bool = excluded.value_bool,')
[void]$docLines.Add('    value_type = excluded.value_type;')
[void]$docLines.Add('')
[void]$docLines.Add('-- Optional usage cap example')
[void]$docLines.Add('insert into pods.plan_capabilities(plan_id, capability_key, value_type, value_int)')
[void]$docLines.Add('values')
[void]$docLines.Add('  (''proteusops_sb_v1'', ''max_monthly_appointments'', ''int'', 200)')
[void]$docLines.Add('on conflict (plan_id, capability_key) do update')
[void]$docLines.Add('set value_int = excluded.value_int,')
[void]$docLines.Add('    value_type = excluded.value_type;')
[void]$docLines.Add('```')
[void]$docLines.Add('')
[void]$docLines.Add('Expected:')
[void]$docLines.Add('- rows exist in pods.plan_tiers and pods.plan_capabilities')
[void]$docLines.Add('')
[void]$docLines.Add('---')
[void]$docLines.Add('')
[void]$docLines.Add('## Step 2 — Identify your org_id')
[void]$docLines.Add('')
[void]$docLines.Add('You must have an org_id for the Node selftests.')
[void]$docLines.Add('')
[void]$docLines.Add('In SQL Editor:')
[void]$docLines.Add('')
[void]$docLines.Add('```sql')
[void]$docLines.Add('select org_id, slug, name')
[void]$docLines.Add('from pods.orgs')
[void]$docLines.Add('order by created_at desc')
[void]$docLines.Add('limit 20;')
[void]$docLines.Add('```')
[void]$docLines.Add('')
[void]$docLines.Add('Record the org_id used by your Node scripts.')
[void]$docLines.Add('')
[void]$docLines.Add('---')
[void]$docLines.Add('')
[void]$docLines.Add('## Step 3 — Run booking selftest (authenticated)')
[void]$docLines.Add('')
[void]$docLines.Add('Command:')
[void]$docLines.Add('')
[void]$docLines.Add('```powershell')
[void]$docLines.Add('node selftest_booking.js')
[void]$docLines.Add('```')
[void]$docLines.Add('')
[void]$docLines.Add('Expected tokens (exact):')
[void]$docLines.Add('')
[void]$docLines.Add('- SELFTEST_RESET_OK')
[void]$docLines.Add('- AVAILABILITY_OK ...')
[void]$docLines.Add('- APPOINTMENT_CREATE_OK ...')
[void]$docLines.Add('- OVERLAP_TEST_EXPECTED_FAIL token=APPOINTMENT_OVERLAP')
[void]$docLines.Add('- TIMEOFF_OK ...')
[void]$docLines.Add('- TIMEOFF_TEST_EXPECTED_FAIL token=STAFF_TIME_OFF_BLOCK')
[void]$docLines.Add('- SELFTEST_DONE')
[void]$docLines.Add('')
[void]$docLines.Add('---')
[void]$docLines.Add('')
[void]$docLines.Add('## Step 4 — Booking disabled negative (service-role flip)')
[void]$docLines.Add('')
[void]$docLines.Add('This proves plan-driven feature gating is enforced in the DB (no UI tricks).')
[void]$docLines.Add('')
[void]$docLines.Add('Command:')
[void]$docLines.Add('')
[void]$docLines.Add('```powershell')
[void]$docLines.Add('node selftest_booking_disabled.js')
[void]$docLines.Add('```')
[void]$docLines.Add('')
[void]$docLines.Add('Expected tokens (exact):')
[void]$docLines.Add('')
[void]$docLines.Add('- PLAN_FLIP_OK plan_id=proteusops_s_v1 recompute=ok')
[void]$docLines.Add('- BOOKING_DISABLED_TEST_EXPECTED_FAIL token=BOOKING_DISABLED')
[void]$docLines.Add('- PLAN_RESTORE_OK plan_id=proteusops_sb_v1 recompute=ok')
[void]$docLines.Add('- SELFTEST_DONE')
[void]$docLines.Add('')
[void]$docLines.Add('---')
[void]$docLines.Add('')
[void]$docLines.Add('## Step 5 — FULL_GREEN one-command run (canonical)')
[void]$docLines.Add('')
[void]$docLines.Add('Command:')
[void]$docLines.Add('')
[void]$docLines.Add('```powershell')
[void]$docLines.Add('powershell.exe -NoProfile -NonInteractive -ExecutionPolicy Bypass -File scripts\selftest_all.ps1')
[void]$docLines.Add('```')
[void]$docLines.Add('')
[void]$docLines.Add('Expected:')
[void]$docLines.Add('- both Node selftests run')
[void]$docLines.Add('- process exits 0')
[void]$docLines.Add('- final token printed: FULL_GREEN_SELFTEST_OK')
[void]$docLines.Add('')
[void]$docLines.Add('---')
[void]$docLines.Add('')
[void]$docLines.Add('## Pass Conditions (Tier-0 proof)')
[void]$docLines.Add('')
[void]$docLines.Add('You have deterministic evidence (stdout logs) that:')
[void]$docLines.Add('')
[void]$docLines.Add('- booking fails when disabled (BOOKING_DISABLED)')
[void]$docLines.Add('- booking succeeds when enabled + paid_active')
[void]$docLines.Add('- overlap/timeoff failures produce stable tokens')
[void]$docLines.Add('- tests are repeatable (reset keeps state clean)')
[void]$docLines.Add('')
[void]$docLines.Add('This doc is canonical for ProteusOps v0.1 selftest procedure.')

Write-Utf8NoBomLf $DocPath ((@($docLines.ToArray()) -join "`n") + "`n")
Parse-GateFile $DocPath
Write-Host ("WROTE+DOC_PARSE_OK: " + $DocPath) -ForegroundColor Green

# -------------------------
# scripts/selftest_all.ps1 (runner)
# -------------------------
$runLines = New-Object System.Collections.Generic.List[string]
[void]$runLines.Add('$ErrorActionPreference="Stop"')
[void]$runLines.Add('Set-StrictMode -Version Latest')
[void]$runLines.Add('')
[void]$runLines.Add('function Die([string]$m){ throw $m }')
[void]$runLines.Add('')
[void]$runLines.Add('$RepoRoot = (Resolve-Path -LiteralPath ".").Path')
[void]$runLines.Add('')
[void]$runLines.Add('# require env vars (Process env)')
[void]$runLines.Add('$need = @("SUPABASE_URL","SUPABASE_ANON_KEY","SUPABASE_SERVICE_ROLE_KEY","TEST_EMAIL","TEST_PASSWORD")')
[void]$runLines.Add('foreach($k in $need){')
[void]$runLines.Add('  $v = [Environment]::GetEnvironmentVariable($k,"Process")')
[void]$runLines.Add('  if([string]::IsNullOrWhiteSpace($v)){ Die ("MISSING_ENV_" + $k) }')
[void]$runLines.Add('}')
[void]$runLines.Add('')
[void]$runLines.Add('$node = (Get-Command node.exe -ErrorAction Stop).Source')
[void]$runLines.Add('')
[void]$runLines.Add('function RunNode([string]$rel){')
[void]$runLines.Add('  $p = Join-Path $RepoRoot $rel')
[void]$runLines.Add('  if(-not (Test-Path -LiteralPath $p -PathType Leaf)){ Die ("MISSING_FILE: " + $p) }')
[void]$runLines.Add('  Write-Host ("RUN: node " + $rel) -ForegroundColor Cyan')
[void]$runLines.Add('  & $node $p | Out-Host')
[void]$runLines.Add('  if($LASTEXITCODE -ne 0){ Die ("NODE_FAIL: " + $rel + " exit=" + $LASTEXITCODE) }')
[void]$runLines.Add('}')
[void]$runLines.Add('')
[void]$runLines.Add('RunNode "selftest_booking.js"')
[void]$runLines.Add('RunNode "selftest_booking_disabled.js"')
[void]$runLines.Add('')
[void]$runLines.Add('Write-Host "FULL_GREEN_SELFTEST_OK" -ForegroundColor Green')

Write-Utf8NoBomLf $RunPath ((@($runLines.ToArray()) -join "`n") + "`n")
Parse-GateFile $RunPath
Write-Host ("WROTE+RUNNER_PARSE_OK: " + $RunPath) -ForegroundColor Green
