-- ProteusOps slice H5 — scheduled provider discovery sync with a machine-only key.
-- Why: provider sync functions must not depend on a human pasting the Supabase secret key (new sb_secret_ keys are
-- not JWTs, so gateway JWT checks can't authenticate them). Instead the database generates a random 256-bit sync key,
-- keeps it ONLY in Vault (sha256 alongside for checking), and pg_cron + pg_net call the sync functions with it.
-- No person ever sees, types, or stores this key. The edge function verifies it through a service-only RPC.
-- Setup on hosted (no secret involved; run once in the SQL editor):
--   select pods_provisioning.svc_hub_sync_setup_v1('https://ytwjyemqlbbebysiopzd.functions.supabase.co', true);

create extension if not exists pg_net with schema extensions;
create extension if not exists pg_cron;

create table if not exists pods_provisioning.hub_sync_config_v1 (
  singleton boolean primary key default true check (singleton),
  functions_base_url text not null check (length(functions_base_url) <= 300 and functions_base_url ~ '^https://[a-z0-9.-]+(:[0-9]+)?$'),
  key_vault_id uuid not null,
  key_sha256 text not null check (key_sha256 ~ '^[a-f0-9]{64}$'),
  schedule text not null default '*/30 * * * *' check (schedule ~ '^[0-9*/,\- ]{9,60}$'),
  scheduled boolean not null default false,
  rotated_at timestamptz not null default now()
);
alter table pods_provisioning.hub_sync_config_v1 enable row level security;
revoke all on pods_provisioning.hub_sync_config_v1 from anon, authenticated;

create table if not exists pods_provisioning.hub_sync_dispatches_v1 (
  dispatch_id bigint generated by default as identity primary key,
  provider_key text not null check (provider_key in ('github')),
  net_request_id bigint,
  dispatched_at timestamptz not null default now()
);
alter table pods_provisioning.hub_sync_dispatches_v1 enable row level security;
revoke all on pods_provisioning.hub_sync_dispatches_v1 from anon, authenticated;

-- (re)generate the key, store it in Vault, optionally (re)schedule the job. Returns no secret material.
create or replace function pods_provisioning.svc_hub_sync_setup_v1(p_functions_base_url text, p_schedule boolean default true,
  p_cron text default '*/30 * * * *')
returns jsonb language plpgsql security definer set search_path = pods_provisioning, public as $fn$
declare v_key text := encode(extensions.gen_random_bytes(32), 'hex'); v_hash text; c pods_provisioning.hub_sync_config_v1%rowtype;
  v_vault uuid; v_url text := rtrim(btrim(coalesce(p_functions_base_url,'')), '/');
begin
  if v_url !~ '^https://[a-z0-9.-]+(:[0-9]+)?$' then raise exception 'HUB_SYNC_BASE_URL_INVALID'; end if;
  v_hash := encode(sha256(convert_to(v_key, 'UTF8')), 'hex');
  select * into c from pods_provisioning.hub_sync_config_v1 where singleton for update;
  if found then
    perform vault.update_secret(c.key_vault_id, v_key);
    v_vault := c.key_vault_id;
  else
    v_vault := vault.create_secret(v_key, 'proteus/hub-sync-key/' || gen_random_uuid()::text, 'ProteusOps hub sync key (machine-only)');
  end if;
  insert into pods_provisioning.hub_sync_config_v1(singleton, functions_base_url, key_vault_id, key_sha256, schedule, scheduled, rotated_at)
  values (true, v_url, v_vault, v_hash, p_cron, coalesce(p_schedule,false), now())
  on conflict (singleton) do update set functions_base_url = excluded.functions_base_url, key_vault_id = excluded.key_vault_id,
    key_sha256 = excluded.key_sha256, schedule = excluded.schedule, scheduled = excluded.scheduled, rotated_at = now();
  if coalesce(p_schedule,false) then
    perform cron.schedule('proteusops-hub-github-sync', p_cron, $c$select pods_provisioning._hub_sync_dispatch_v1('github')$c$);
  elsif exists (select 1 from cron.job where jobname = 'proteusops-hub-github-sync') then
    perform cron.unschedule('proteusops-hub-github-sync');
  end if;
  return jsonb_build_object('ok', true, 'base_url', v_url, 'scheduled', coalesce(p_schedule,false), 'schedule', p_cron,
                            'key_fingerprint', 'sha256:' || left(v_hash, 8));
end $fn$;

-- called by pg_cron (or manually by an operator) to fire one sync
create or replace function pods_provisioning._hub_sync_dispatch_v1(p_provider_key text)
returns jsonb language plpgsql security definer set search_path = pods_provisioning, public as $fn$
declare c pods_provisioning.hub_sync_config_v1%rowtype; v_key text; v_req bigint;
begin
  if p_provider_key is distinct from 'github' then raise exception 'HUB_SYNC_PROVIDER_UNSUPPORTED'; end if;
  select * into c from pods_provisioning.hub_sync_config_v1 where singleton;
  if not found then return jsonb_build_object('ok', false, 'error', 'HUB_SYNC_NOT_CONFIGURED'); end if;
  select decrypted_secret into v_key from vault.decrypted_secrets where id = c.key_vault_id;
  if v_key is null then return jsonb_build_object('ok', false, 'error', 'HUB_SYNC_KEY_MISSING'); end if;
  v_req := net.http_post(url := c.functions_base_url || '/github-sync',
                         body := '{}'::jsonb,
                         headers := jsonb_build_object('content-type', 'application/json', 'x-proteus-sync-key', v_key),
                         timeout_milliseconds := 60000);
  insert into pods_provisioning.hub_sync_dispatches_v1(provider_key, net_request_id) values (p_provider_key, v_req);
  return jsonb_build_object('ok', true, 'net_request_id', v_req);
end $fn$;

-- service-only: does this presented key match the stored one?
create or replace function pods_provisioning.svc_hub_sync_key_check_v1(p_key text)
returns boolean language sql stable security definer set search_path = pods_provisioning, public as $fn$
  select coalesce(length(p_key) = 64 and
    (select key_sha256 from pods_provisioning.hub_sync_config_v1 where singleton) = encode(sha256(convert_to(p_key, 'UTF8')), 'hex'), false) $fn$;

-- operator read: last dispatches with HTTP outcome (no secrets)
create or replace function pods_provisioning.svc_hub_sync_status_v1()
returns jsonb language sql stable security definer set search_path = pods_provisioning, public as $fn$
  select jsonb_build_object(
    'configured', exists (select 1 from pods_provisioning.hub_sync_config_v1),
    'config', (select jsonb_build_object('base_url', functions_base_url, 'schedule', schedule, 'scheduled', scheduled,
                 'key_fingerprint', 'sha256:' || left(key_sha256, 8), 'rotated_at', rotated_at) from pods_provisioning.hub_sync_config_v1),
    'recent', coalesce((select jsonb_agg(x order by x->>'dispatched_at' desc) from (
        select jsonb_build_object('provider', d.provider_key, 'dispatched_at', d.dispatched_at, 'net_request_id', d.net_request_id,
                 'status_code', r.status_code, 'error', r.error_msg, 'body', left(r.content, 2000)) x
          from pods_provisioning.hub_sync_dispatches_v1 d left join net._http_response r on r.id = d.net_request_id
         order by d.dispatched_at desc limit 10) s), '[]'::jsonb)) $fn$;

create or replace function public.svc_hub_sync_key_check_v1(p_key text)
returns boolean language sql stable security definer set search_path = pods_provisioning, public as $fn$
  select pods_provisioning.svc_hub_sync_key_check_v1(p_key) $fn$;

do $$ declare s text; begin
  foreach s in array array['pods_provisioning.svc_hub_sync_setup_v1(text,boolean,text)', 'pods_provisioning._hub_sync_dispatch_v1(text)',
    'pods_provisioning.svc_hub_sync_key_check_v1(text)', 'pods_provisioning.svc_hub_sync_status_v1()',
    'public.svc_hub_sync_key_check_v1(text)'] loop
    execute format('revoke all on function %s from public, anon, authenticated', s);
    execute format('grant execute on function %s to service_role', s);
  end loop;
end $$;

-- ---------- selftest (all changes rolled back in a subtransaction; never touches a live config) ----------
create or replace function pods_provisioning.rpc_selftest_hub_sync_scheduler_v1()
returns jsonb language plpgsql security definer set search_path = pods_provisioning, public as $fn$
declare r jsonb; v_key text; t_setup bool := false; t_no_secret_returned bool := false; t_good bool := false; t_bad bool := false;
  t_short bool := false; t_rotate bool := false; t_bad_url bool := false; t_unsched bool := false; t_clients bool := false;
  t_rls bool := false; v_ok bool; v_old text;
begin
  begin
    r := pods_provisioning.svc_hub_sync_setup_v1('https://selftest.invalid', false);
    t_setup := (r->>'ok')::boolean and not (r->>'scheduled')::boolean;
    t_no_secret_returned := r::text !~ '[a-f0-9]{64}';
    select s.decrypted_secret into v_key from vault.decrypted_secrets s
      join pods_provisioning.hub_sync_config_v1 c on c.key_vault_id = s.id;
    t_good := pods_provisioning.svc_hub_sync_key_check_v1(v_key);
    t_bad := not pods_provisioning.svc_hub_sync_key_check_v1(repeat('0', 64));
    t_short := not pods_provisioning.svc_hub_sync_key_check_v1('') and not pods_provisioning.svc_hub_sync_key_check_v1(null);
    v_old := v_key;
    perform pods_provisioning.svc_hub_sync_setup_v1('https://selftest.invalid', false);
    t_rotate := not pods_provisioning.svc_hub_sync_key_check_v1(v_old);
    begin perform pods_provisioning.svc_hub_sync_setup_v1('http://selftest.invalid', false);
    exception when others then t_bad_url := sqlerrm like '%HUB_SYNC_BASE_URL_INVALID%'; end;
    t_unsched := not exists (select 1 from cron.job where jobname = 'proteusops-hub-github-sync' and command like '%selftest%');
    raise exception 'SELFTEST_ROLLBACK';
  exception when others then
    if sqlerrm <> 'SELFTEST_ROLLBACK' then raise; end if;
  end;
  t_clients := not has_function_privilege('authenticated', 'public.svc_hub_sync_key_check_v1(text)', 'execute')
           and not has_function_privilege('anon', 'public.svc_hub_sync_key_check_v1(text)', 'execute')
           and not has_function_privilege('authenticated', 'pods_provisioning.svc_hub_sync_setup_v1(text,boolean,text)', 'execute')
           and not has_function_privilege('authenticated', 'pods_provisioning._hub_sync_dispatch_v1(text)', 'execute');
  select bool_and(c.relrowsecurity) into t_rls from pg_class c join pg_namespace n on n.oid = c.relnamespace
   where n.nspname = 'pods_provisioning' and c.relname in ('hub_sync_config_v1','hub_sync_dispatches_v1');
  v_ok := t_setup and t_no_secret_returned and t_good and t_bad and t_short and t_rotate and t_bad_url and t_unsched
      and t_clients and coalesce(t_rls,false);
  return jsonb_build_object('ok', v_ok,
    'token', case when v_ok then 'PROTEUSOPS_HUB_SYNC_SCHEDULER_OK' else 'PROTEUSOPS_HUB_SYNC_SCHEDULER_FAIL' end,
    'setup', t_setup, 'no_secret_returned', t_no_secret_returned, 'key_accepted', t_good, 'wrong_key_rejected', t_bad,
    'empty_key_rejected', t_short, 'rotation_invalidates_old', t_rotate, 'https_only', t_bad_url,
    'selftest_never_schedules', t_unsched, 'clients_blocked', t_clients, 'rls_on', t_rls);
end $fn$;
revoke all on function pods_provisioning.rpc_selftest_hub_sync_scheduler_v1() from public, anon, authenticated;
grant execute on function pods_provisioning.rpc_selftest_hub_sync_scheduler_v1() to service_role;
